name: Build iOS IPA

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Show Xcode
        run: xcodebuild -version

      - name: Build app
        run: |
          xcodebuild clean build \
          -scheme MangaPlayer \
          -sdk iphoneos \
          CODE_SIGNING_ALLOWED=NO

      - name: Archive
        run: |
          xcodebuild archive \
          -scheme MangaPlayer \
          -archivePath build/app.xcarchive \
          CODE_SIGNING_ALLOWED=NO

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
          -archivePath build/app.xcarchive \
          -exportPath build \
          -exportOptionsPlist Resources/ExportOptions.plist

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ipa
          path: build/*.ipa
